In [1]:
import numpy as np


A = np.array([
    [2/5, 0, 0, 1/5],
    [0, 2/5, 3/10, 1/5],
    [0, 3/10, 2/5, 1/5],
    [3/5, 3/10, 3/10, 2/5]
])
A

array([[0.4, 0. , 0. , 0.2],
       [0. , 0.4, 0.3, 0.2],
       [0. , 0.3, 0.4, 0.2],
       [0.6, 0.3, 0.3, 0.4]])

## Part a

In [2]:
b = np.array([12, 25, 26, 37])
b

array([12, 25, 26, 37])

In [3]:
np.linalg.solve(A, b)

array([10., 20., 30., 40.])

## Part b

In [4]:
x = np.array([20, 20, 20, 40])
x

array([20, 20, 20, 40])

In [5]:
np.dot(A, x)

array([16., 22., 22., 40.])